### ISSUE TITLE
[Feature] Warnings for out of date files

### ISSUE THREAD

**Issue by HebaruSan** [DasSkelett/AVC-VersionFileValidator#1]
## Motivation

Most of the time a new release is intended for the latest version of KSP, and sometimes the metadata doesn't get updated.

https://forum.kerbalspaceprogram.com/index.php?/topic/162477-18-early-bird-020/&do=findComment&comment=3720010

## Suggestion

We could download `builds.json` and check whether a .version file indicates compatibility with the highest version, and if not, then raise a non-fatal warning (if there is such a thing with a GitHub Action).

**Comment by DasSkelett** [comment]
If I understand the docs correctly, I can write warning messages in the log:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-a-warning-message-warning

However the status that is set to the pull request seems to be binary, 0 or everything else, where 0 means success and !0 means failure:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#setting-an-actions-status-using-exit-codes

I'm not sure if it should set the PR status to failed when the KSP version is not the newest, there might be some cases where they have separate branches for backports (I took a look around in the repos of some known mods with backports, I could find Kopernicus doing it like that).

On the other hand I could make the behavior configurable via an input variable, like `fail_on_outdated_KSP_version` which could default to `true`.

**Comment by HebaruSan** [comment]
> if it should set the PR status to failed when the KSP version is not the newest

Definitely not; if there isn't an intermediate "warning" state, then this should be a pass/success.

**Comment by DasSkelett** [comment]
Implemented in #5. It displays a warning in the lower left corner of the workflow log page:
`The file awesomemod.version doesn't indicate compatibility with the latest version of KSP (1.8.1.2694). Did you forget to update it?`

![grafik](https://user-images.githubusercontent.com/28812678/73045197-3cc32200-3e6d-11ea-827e-45b0df7f8a8c.png)
(Ignore all the additional warnings and error messages, the test run encounters a lot of invalid files of course)

It would be really neat if Github would show warning messages on the PR page itself. Only way to display the more prominently is to create comments on the PR via API, but that's pretty intrusive and too much IMHO.
Plus, I would have to learn more about the GH API, and I don't want to right now :man_shrugging:
